# Generated by Django 4.0.5 on 2022-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_followers_followers_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers_number',
        ),
        migrations.RemoveField(
            model_name='following',
            name='following_number',
        ),
        migrations.AddField(
            model_name='user',
            name='followers_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_number',
            field=models.IntegerField(default=0),
        ),
    ]
